"""Render the CIRCLE THE SQUARE end title as real type and scroll it up over the final shot.

The title is NOT generated by Veo. Baked-in lettering warps the moment the model has to
redraw it, so the closing shot is rendered clean (no text) and the title is composited here
as a pre-rendered PNG. That keeps the letterforms perfectly sharp and gives frame-accurate
control over when the move starts, how fast it climbs and where it leaves frame.

ffmpeg's drawtext filter segfaults on this machine (no fontconfig), hence PIL -> PNG -> overlay.

Usage:
    python build_title_scroll.py --preview          # still frames of each font option
    python build_title_scroll.py --clip T26_title_card.mp4
"""

import argparse
import os
import subprocess
import sys

from PIL import Image, ImageDraw, ImageFont

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FONTS_DIR = r"C:\Windows\Fonts"

TITLE_TEXT = "CIRCLE THE SQUARE"
FRAME_W, FRAME_H = 1920, 1080

# Heavy faces available on this machine, widest-stroke first.
FONT_OPTIONS = {
    "impact": ("impact.ttf", 1.00),   # condensed heavy - closest to the plate's own title
    "black": ("ariblk.ttf", 0.80),    # Arial Black - wider, rounder, very heavy
    "segoe": ("seguibl.ttf", 0.82),   # Segoe UI Black - cleaner, more modern
}

# Title styling. The plate's own title is white with a hard dark edge, so match that.
FILL = (255, 255, 255, 255)
STROKE = (12, 16, 26, 255)
STROKE_W = 14           # heavy outline so it holds up over the lit glazing
SHADOW_OFFSET = 10
SHADOW = (0, 0, 0, 130)
TRACKING = 0.06         # extra letter spacing as a fraction of font size


def load_font(key, target_width):
    """Size the chosen face so the title spans target_width pixels."""
    name, scale = FONT_OPTIONS[key]
    path = os.path.join(FONTS_DIR, name)
    if not os.path.exists(path):
        sys.exit(f"Font not found: {path}")

    size = 100
    font = ImageFont.truetype(path, size)
    while True:
        w = measure(TITLE_TEXT, font, size)
        if w >= target_width * scale or size > 900:
            break
        size += 10
        font = ImageFont.truetype(path, size)
    return font, size


def measure(text, font, size):
    tracking = int(size * TRACKING)
    return sum(font.getbbox(ch)[2] - font.getbbox(ch)[0] + tracking for ch in text) - tracking


def render_title_png(key, out_path, target_width=None):
    """Transparent PNG of the title, tightly cropped with room for stroke and shadow."""
    target_width = target_width or int(FRAME_W * 0.86)
    font, size = load_font(key, target_width)
    tracking = int(size * TRACKING)

    pad = STROKE_W * 2 + SHADOW_OFFSET + 20
    width = measure(TITLE_TEXT, font, size) + pad * 2
    height = int(size * 1.6) + pad * 2

    img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    # Draw letter by letter so the tracking is real rather than faked by the renderer.
    def draw_run(dx, dy, fill, stroke_fill=None, stroke_width=0):
        x = pad + dx
        for ch in TITLE_TEXT:
            draw.text(
                (x, pad + dy), ch, font=font, fill=fill,
                stroke_fill=stroke_fill, stroke_width=stroke_width,
            )
            bbox = font.getbbox(ch)
            x += bbox[2] - bbox[0] + tracking

    draw_run(SHADOW_OFFSET, SHADOW_OFFSET, SHADOW)
    draw_run(0, 0, FILL, STROKE, STROKE_W)

    img.crop(img.getbbox()).save(out_path)
    return out_path


def preview(plate, out_path):
    """One image showing every font option composited over the closing plate."""
    if not os.path.exists(plate):
        sys.exit(f"Plate not found: {plate}")

    base = Image.open(plate).convert("RGBA").resize((FRAME_W, FRAME_H))
    tiles = []
    for key in FONT_OPTIONS:
        png = os.path.join(BASE_DIR, f"_title_{key}.png")
        render_title_png(key, png)
        title = Image.open(png).convert("RGBA")

        tile = base.copy()
        x = (FRAME_W - title.width) // 2
        y = int(FRAME_H * 0.60)
        tile.alpha_composite(title, (x, y))
        tiles.append(tile.resize((FRAME_W // 2, FRAME_H // 2)))

    sheet = Image.new("RGBA", (FRAME_W // 2, (FRAME_H // 2) * len(tiles)))
    for i, tile in enumerate(tiles):
        sheet.paste(tile, (0, (FRAME_H // 2) * i))
    sheet.convert("RGB").save(out_path, quality=92)
    print(f"Preview written: {out_path}")
    print("Top to bottom: " + ", ".join(FONT_OPTIONS))


def scroll_over_clip(clip, font_key, out_path, start=1.2, travel_seconds=4.0, rest_y=0.60):
    """Composite the title over a clip, travelling from rest_y up and off the top."""
    png = os.path.join(BASE_DIR, f"_title_{font_key}.png")
    render_title_png(font_key, png)
    title = Image.open(png)

    y0 = int(FRAME_H * rest_y)
    y1 = -title.height - 20  # fully clear of the top edge

    # Hold at y0 until `start`, then climb linearly to y1 over travel_seconds.
    expr = (
        f"if(lt(t,{start:.2f}),{y0},"
        f"max({y1},{y0}-({y0}-({y1}))*(t-{start:.2f})/{travel_seconds:.2f}))"
    )

    cmd = [
        "ffmpeg", "-y", "-i", clip, "-i", png,
        "-filter_complex",
        f"[0:v]scale={FRAME_W}:{FRAME_H}:force_original_aspect_ratio=increase,"
        f"crop={FRAME_W}:{FRAME_H}[bg];"
        f"[bg][1:v]overlay=x=(W-w)/2:y='{expr}':eval=frame[v]",
        "-map", "[v]", "-c:v", "libx264", "-crf", "18", "-preset", "medium",
        "-pix_fmt", "yuv420p", out_path,
    ]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if res.returncode != 0:
        sys.exit(f"[ERROR] ffmpeg:\n{res.stderr[-2000:]}")
    print(f"Title scroll written: {out_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true", help="render font options over the plate")
    ap.add_argument("--clip", help="clip filename inside clips/cartoon to title")
    ap.add_argument("--font", default="impact", choices=list(FONT_OPTIONS))
    ap.add_argument("--start", type=float, default=1.2, help="seconds before the climb starts")
    ap.add_argument("--travel", type=float, default=4.0, help="seconds to climb off frame")
    args = ap.parse_args()

    if args.preview:
        preview(
            os.path.join(BASE_DIR, "location-refs", "cartoon-plates",
                         "L01_establishing_courtyard_dusk.jpg"),
            os.path.join(BASE_DIR, "_title_preview.jpg"),
        )
        return

    if not args.clip:
        sys.exit("Give --clip <file in clips/cartoon> or --preview")

    clip = os.path.join(BASE_DIR, "clips", "cartoon", args.clip)
    if not os.path.exists(clip):
        sys.exit(f"Clip not found: {clip}")

    out = os.path.join(BASE_DIR, "clips", "cartoon",
                       os.path.splitext(args.clip)[0] + "_titled.mp4")
    scroll_over_clip(clip, args.font, out, start=args.start, travel_seconds=args.travel)


if __name__ == "__main__":
    main()
