"""
Circle the Square — Qwen3-TTS Synthesis Script

Two-phase pipeline, per character:
  1. REFERENCE — the character's first line is synthesized once via VoiceDesign
     (instruct/text-controlled accent, from CARTOON_CAST_BIBLE.md).
  2. CLONE — every other line for that character is generated by cloning the
     reference take's exact voice identity (Qwen3-TTS "Base" model,
     generate_voice_clone), NOT by calling VoiceDesign again per line.

Why: VoiceDesign samples a brand-new voice from the text description on
every single call — same instruct, different random voice each time. That
is what caused different mp3s for the same character to sound like
different people (found 2026-08-28, Christina/Jan). Cloning from one
approved reference line keeps the whole character consistent. Named
CustomVoice presets (Ryan/Serena/Vivian/Dylan/Uncle_Fu) were tried first and
dropped entirely: they're fixed voices but don't reliably land a specified
accent (e.g. "Serena" read Asian-accented instead of British RP).

Both phases reject and retry any take whose pitch (F0) is flat/monotone —
that pattern (e.g. a 6 Hz range dead-flat take) is a real TTS failure mode,
not just "different-sounding", and previously produced Christina's F01
"male robot" line.

Outputs to: C:\\AI\\Circle the Square\\docs\\audio-refs\\
Naming:  {character}_{index}.mp3  e.g. jan_01.mp3, christina_01.mp3
That folder — not a sibling audio-refs/ at the repo root — is the actual
document root the bubble studio's HTTP server (docs/) serves from; a
repo-root copy is never reachable by the page's "../audio-refs/..." URLs
(found 2026-08-28 after regenerating the wrong folder for an hour).
"""

import sys, os
from pathlib import Path
import torch
import soundfile as sf
import numpy as np
import librosa

# Force UTF-8 stdout so Unicode prints work in Windows console
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

# ── ComfyUI paths ────────────────────────────────────────────────────────────
COMFY_ROOT   = Path(r"C:\ai\ComfyUI\ComfyUI")
COMFY_NODES  = COMFY_ROOT / "custom_nodes" / "ComfyUI-QwenTTS"
QwenTTS_DIR  = COMFY_NODES / "qwen_tts"

# Must chdir to ComfyUI root so 'comfy' package resolves
os.chdir(str(COMFY_ROOT))

for _p in [str(COMFY_ROOT), str(COMFY_NODES), str(QwenTTS_DIR)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from AILab_QwenTTS import _load_qwen3_model, _ensure_qwen_package

# ── Output ─────────────────────────────────────────────────────────────────────
OUT_DIR = Path(r"C:\AI\Circle the Square\docs\audio-refs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Quality gate ───────────────────────────────────────────────────────────────
MIN_PITCH_RANGE_HZ = 15.0  # below this, a take reads as flat/monotone -- reject and retry
MAX_RETRIES = 4

def measure_pitch(path: Path):
    """Mean F0 and pitch range (Hz) of a wav/mp3. Returns (None, None) if unvoiced/silent."""
    y, sr = librosa.load(str(path), sr=None)
    f0, voiced_flag, voiced_prob = librosa.pyin(
        y, fmin=librosa.note_to_hz("C2"), fmax=librosa.note_to_hz("C7"), sr=sr
    )
    valid = f0[~np.isnan(f0)]
    if len(valid) == 0:
        return None, None
    return float(np.mean(valid)), float(np.max(valid) - np.min(valid))


def wav_to_mp3(wav_path: Path, mp3_path: Path, bitrate: str = "128k"):
    from pydub import AudioSegment
    AudioSegment.from_wav(str(wav_path)).export(str(mp3_path), format="mp3", bitrate=bitrate)
    wav_path.unlink(missing_ok=True)


def generate_reference(model, instruct: str, text: str, out_path: Path) -> bool:
    """VoiceDesign, quality-gated with retries. Returns True on success."""
    wav_path = out_path.with_suffix(".wav")
    for attempt in range(1, MAX_RETRIES + 1):
        print(f"    attempt {attempt}: '{text[:50]}'")
        wavs, sr = model.generate_voice_design(text=text, instruct=instruct, language="english")
        sf.write(str(wav_path), wavs[0], sr)
        mean_f0, rng = measure_pitch(wav_path)
        if mean_f0 is None:
            print("      no pitch detected -- retrying")
            continue
        print(f"      mean F0={mean_f0:.1f} Hz, range={rng:.1f} Hz")
        if rng >= MIN_PITCH_RANGE_HZ:
            wav_to_mp3(wav_path, out_path)
            print(f"      ACCEPTED -> {out_path.name} ({out_path.stat().st_size/1024:.1f} KB)")
            return True
        print("      REJECTED (flat/monotone) -- retrying")
    print(f"    FAILED after {MAX_RETRIES} attempts")
    return False


def generate_clone(model, voice_clone_prompt, text: str, out_path: Path) -> bool:
    """Voice-clone from a prebuilt prompt, quality-gated with retries. Returns True on success."""
    wav_path = out_path.with_suffix(".wav")
    for attempt in range(1, MAX_RETRIES + 1):
        print(f"    attempt {attempt}: '{text[:50]}'")
        wavs, sr = model.generate_voice_clone(text=text, language="english", voice_clone_prompt=voice_clone_prompt)
        sf.write(str(wav_path), wavs[0], sr)
        mean_f0, rng = measure_pitch(wav_path)
        if mean_f0 is None:
            print("      no pitch detected -- retrying")
            continue
        print(f"      mean F0={mean_f0:.1f} Hz, range={rng:.1f} Hz")
        if rng >= MIN_PITCH_RANGE_HZ:
            wav_to_mp3(wav_path, out_path)
            print(f"      ACCEPTED -> {out_path.name} ({out_path.stat().st_size/1024:.1f} KB)")
            return True
        print("      REJECTED (flat/monotone) -- retrying")
    print(f"    FAILED after {MAX_RETRIES} attempts")
    return False


# ── Character roster ─────────────────────────────────────────────────────────
# "lines" are 1-indexed (lines[0] -> {character}_01.mp3, the reference take).
# "pinned" is a set of 1-based indices to NEVER touch, even if missing/absent
# from disk right now -- e.g. a deliberately hand-rerolled one-off delivery
# that should not be regenerated with the character's default instruct.
CHARACTERS = {
    "jan": {
        "instruct": (
            "pitch: High, sharp, strained tenor, male.\n"
            "speed: Fast, erratic.\n"
            "emotion: Anxious, pompous, hysterical, angry.\n"
            "personality: Blustering, insecure tyrant.\n"
            "accent: British Received Pronunciation."
        ),
        # Verbatim from FRAMES in docs/f01_bubble_studio.html, in AUDIO_MAP order
        # (F02, F04, F06a, F06b, F08, F10, F12, F14, F16, F20, F24).
        "lines": [
            "Barely. Another day dealing with these morons at the office.",   # F02 (reference)
            "I'm listening.",                                                # F04
            "I am liking the idea of this so far.",                         # F06a
            "This is exactly the kind of strategic thinking.",              # F06b
            "Great. Make it so.",                                            # F08 -- PINNED, see below
            "You never seen Star Trek Next Generation?",                    # F10
            "Fine, just make it happen.",                                    # F12
            "Jesus! Everyone thinks they know better than me!",             # F14
            "GET OUT NOW YOU STUPID COW! JUST GET THAT DAMN MEETING ORGANISED!",  # F16
            "BLOODY HELL SHAWRUN. NOCK ON THE DOOR WILL YOU!",              # F20 -- "NOCK"/"SHAWRUN" are deliberate
                                                                              #        phonetic respellings: TTS
                                                                              #        choked on silent-K "KNOCK"
                                                                              #        ("k not on the door"), and
                                                                              #        misread "Sharon" a few ways
                                                                              #        in a row ("SHARR-on", then
                                                                              #        "Sharoon" still wrong) before
                                                                              #        landing on "Shawrun" per QA.
                                                                              #        Both respellings are
                                                                              #        audio-only; captions stay
                                                                              #        "KNOCK"/"Sharon" in
                                                                              #        docs/f01_bubble_studio.html.
            "I really don't have time for this now Shawrun.",                # F24 -- "Shawrun", see F20 note above
        ],
        # jan_05.mp3 (index 5, F08) is a deliberate one-off Picard-styled take
        # ("Great. Make it so." is the Star Trek callback F10 sets up) — never
        # regenerate it from Jan's default instruct or clone.
        "pinned": {5},
    },
    "christina": {
        "instruct": (
            "pitch: Low-to-mid, crisp, level alto, distinctly female.\n"
            "speed: Measured, unhurried, steady.\n"
            "emotion: Cold, deadpan, calm.\n"
            "personality: Dry, unflappable corporate strategist.\n"
            "accent: British London Received Pronunciation, female voice."
        ),
        # Verbatim from FRAMES, in AUDIO_MAP order (F01,F03,F05,F07,F09,F11,F13,F15).
        "lines": [
            "Morning Jan. Survive the weekend?",                              # F01 (reference)
            "I see. Well, I might be able to help with that.",               # F03
            "Well, every two weeks on a Friday we do a breakfast meeting.",  # F05
            "Thought you would like it.",                                    # F07
            "I am sorry?.........What?",                                      # F09 -- extra pause/beat, per QA
            "Shockingly no.",                                                # F11
            "Is this another one of your poorly rehearsed presentations?",  # F13
            "Made Up Place?",                                                # F15
        ],
        "pinned": set(),
    },
    "sharon": {
        "instruct": (
            "pitch: Warm, mid-range, confident, female.\n"
            "speed: Casual, relaxed.\n"
            "emotion: Unbothered, amused, grounded.\n"
            "personality: Confident, unflappable opportunist.\n"
            "accent: Scottish."
        ),
        # Verbatim from FRAMES, in AUDIO_MAP order (F23, F25). F24 sits between them
        # but is a Jan line, not Sharon — see jan's F24 entry above.
        "lines": [
            "I hear Christina is doing breakfast meetings now.",  # F23 (reference)
            "Well I have needs too Jan that must be met.",        # F25
        ],
        "pinned": set(),
    },
    # ── Chris & Rick ──────────────────────────────────────────────────────────
    # NOT YET VERIFIED against FRAMES (Scene 2) — same class of caption/audio
    # drift found and fixed above for jan/christina/sharon is likely present
    # here too (F31 in AUDIO_MAP is actually a Jan line, not Chris, and was
    # removed from the Chris block there pending a proper Scene 2 pass). Fix
    # the "lines" lists against FRAMES before trusting these outputs.
    "chris": {
        "instruct": (
            "pitch: Bright, conversational baritone, male.\n"
            "speed: Quick-witted, rising punchline timing.\n"
            "emotion: Sarcastic, amused.\n"
            "personality: Smart-mouthed office wit.\n"
            "accent: South London/Estuary English."
        ),
        "lines": [
            "You are dreaming Jan. Inception is the name of a film about dreams Jan.",
            "Is that a whiteboard in your office? I can see it from here.",
            "Christina mentioned something about breakfast pastries. You know I can't resist.",
            "No, no, I just came to ask about the fire safety procedures. That's all.",
        ],
        "pinned": set(),
    },
    "rick": {
        "instruct": (
            "pitch: Deep, gravelly bass-baritone, male.\n"
            "speed: Slow, deliberate monotone.\n"
            "emotion: Flat, unhurried, unbothered.\n"
            "personality: Blunt, matter-of-fact realist.\n"
            "accent: Flat Midlands/East Anglian English."
        ),
        "lines": [
            "No relax, he will be out for a while. I think we need the police here.",
            "The blinds slammed shut on their own. I saw it happen.",
            "Just doing my rounds. Everything is under control.",
        ],
        "pinned": set(),
    },
    # ── Not yet in FRAMES / not yet on screen (future scenes) ───────────────
    "maureen": {
        "instruct": (
            "pitch: Medium, warm, slightly husky.\n"
            "speed: Steady, unhurried.\n"
            "emotion: Kind, maternal, no-nonsense.\n"
            "personality: Reliable, good-humoured caretaker.\n"
            "accent: East Anglian (Norfolk/Cambridge region)."
        ),
        "lines": [
            "Breakfast is served in the main hall at eight, dear. Don't be late.",
            "I've laid on an extra tray. Looks like it's going to be a busy one.",
        ],
        "pinned": set(),
    },
    "gemma": {
        "instruct": (
            "pitch: Clear, mid-range, pleasant.\n"
            "speed: Moderate, efficient.\n"
            "emotion: Polite, attentive.\n"
            "personality: Organised, welcoming.\n"
            "accent: Standard Southern English."
        ),
        "lines": [
            "Jan, there's a call for you on line two. Says it's urgent.",
            "The visitor from PRISM is waiting in reception.",
        ],
        "pinned": set(),
    },
    "priya": {
        "instruct": (
            "pitch: Warm, melodic, mid-range.\n"
            "speed: Measured, thoughtful.\n"
            "emotion: Calm, observant.\n"
            "personality: Quietly confident, analytical.\n"
            "accent: Received Southern British with subtle Indian influence."
        ),
        "lines": [
            "I think there may have been some miscommunication about the agenda.",
            "The data from last quarter is in the shared drive if you need it.",
        ],
        "pinned": set(),
    },
    "barbara": {
        "instruct": (
            "pitch: Low, measured, dignified.\n"
            "speed: Slow, deliberate.\n"
            "emotion: Dry wit, unflappable.\n"
            "personality: Experienced, sardonic observer.\n"
            "accent: RP with faint Midlands undertone."
        ),
        "lines": [
            "I've seen a few reorganisations in my time, Jan. This one feels familiar.",
            "Would you like me to book the conference room for later?",
        ],
        "pinned": set(),
    },
    "dev": {
        "instruct": (
            "pitch: Deep, resonant, confident baritone.\n"
            "speed: Even, deliberate.\n"
            "emotion: Composed, direct.\n"
            "personality: Steady, reliable.\n"
            "accent: British West African / RP blend."
        ),
        "lines": [
            "I've run the diagnostics. The server is stable for now.",
            "If you need the file transferred, I can handle that.",
        ],
        "pinned": set(),
    },
    "tomasz": {
        "instruct": (
            "pitch: Mid-range, slightly gruff.\n"
            "speed: Slow to measured.\n"
            "emotion: Practical, no fuss.\n"
            "personality: Straightforward, physically imposing.\n"
            "accent: East European English (Polish influence)."
        ),
        "lines": [
            "The delivery came. I put it in the store room.",
            "If you need a hand with anything heavy, just say.",
        ],
        "pinned": set(),
    },
}

# ── Main ──────────────────────────────────────────────────────────────────────
_ensure_qwen_package()
ModelClass = _load_qwen3_model()
if ModelClass is None:
    print("ERROR: Could not load Qwen3-TTS model. Check AILab_QwenTTS installation.")
    sys.exit(1)

total_generated = 0
total_skipped = 0
total_failed = 0

# ── Phase 1: reference line per character (VoiceDesign) ─────────────────────
print(f"\n{'='*60}\nPHASE 1 — reference lines (VoiceDesign)\n{'='*60}")
vd_model_dir = COMFY_ROOT / "models" / "TTS" / "Qwen3-TTS" / "Qwen3-TTS-12Hz-1.7B-VoiceDesign"
vd_model = None

for character, cfg in CHARACTERS.items():
    ref_path = OUT_DIR / f"{character}_01.mp3"
    if ref_path.exists():
        print(f"[{character}] [SKIP] {ref_path.name} (already exists)")
        total_skipped += 1
        continue
    if 1 in cfg["pinned"]:
        print(f"[{character}] [SKIP] {ref_path.name} (pinned, hand-authored)")
        continue
    if vd_model is None:
        print(f"Loading VoiceDesign model from {vd_model_dir} ...")
        vd_model = ModelClass.from_pretrained(
            str(vd_model_dir),
            dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            device_map="cuda" if torch.cuda.is_available() else "cpu",
        )
    print(f"[{character}] generating reference {ref_path.name}")
    ok = generate_reference(vd_model, cfg["instruct"], cfg["lines"][0], ref_path)
    if ok:
        total_generated += 1
    else:
        total_failed += 1

if vd_model is not None:
    del vd_model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

# ── Phase 2: clone every other line from the reference ───────────────────────
print(f"\n{'='*60}\nPHASE 2 — clone remaining lines (Base / generate_voice_clone)\n{'='*60}")
base_model_dir = COMFY_ROOT / "models" / "TTS" / "Qwen3-TTS" / "Qwen3-TTS-12Hz-1.7B-Base"
base_model = None

for character, cfg in CHARACTERS.items():
    lines = cfg["lines"]
    pinned = cfg["pinned"]
    ref_path = OUT_DIR / f"{character}_01.mp3"

    # Which of this character's other lines actually need generating?
    todo = [
        (i, text) for i, text in enumerate(lines[1:], start=2)
        if i not in pinned and not (OUT_DIR / f"{character}_{i:02d}.mp3").exists()
    ]
    if not todo:
        continue
    if not ref_path.exists():
        print(f"[{character}] SKIPPING {len(todo)} line(s) -- no reference {ref_path.name} to clone from")
        total_failed += len(todo)
        continue

    if base_model is None:
        print(f"Loading Base (voice-clone) model from {base_model_dir} ...")
        base_model = ModelClass.from_pretrained(
            str(base_model_dir),
            dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            device_map="cuda" if torch.cuda.is_available() else "cpu",
        )

    print(f"\n[{character}] building voice-clone prompt from {ref_path.name}")
    prompt_items = base_model.create_voice_clone_prompt(
        ref_audio=str(ref_path),
        ref_text=lines[0],
        x_vector_only_mode=False,
    )

    for i, text in todo:
        out_path = OUT_DIR / f"{character}_{i:02d}.mp3"
        print(f"  [{character}_{i:02d}]")
        ok = generate_clone(base_model, prompt_items, text, out_path)
        if ok:
            total_generated += 1
        else:
            total_failed += 1

if base_model is not None:
    del base_model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

print(f"\n{'='*60}")
print(f"Done. {total_generated} generated, {total_skipped} skipped (already existed), {total_failed} failed.")
print(f"  Output: {OUT_DIR}")
